### ISSUE TITLE
Not found getmonday.sh

### ISSUE THREAD

**Issue by stormcat24** [eko/monday#15]
It seems that `https://composieux.fr/getmonday.sh` is not found now. 
So I installed monday with other method.

**Steps for Reproduction**

- `curl -i https://composieux.fr/getmonday.sh`

**Expected behavior**:

It returns content of `getmonday.sh`.

**Actual behavior**:

```bash
curl -i https://composieux.fr/getmonday.sh
HTTP/2 404
server: nginx/1.10.3
date: Mon, 05 Aug 2019 02:51:51 GMT
content-type: text/html; charset=utf-8
content-length: 169

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```

**Platforms**:

macOS 10.13.16

Include browser, operating system and respective versions

**Versions**:

README in master

**Comment by eko** [comment]
Hi @stormcat24,

I put the script back ;)

Thank you for your report and sorry about that.

**Comment by stormcat24** [comment]
Thanks 🙏
