### ISSUE TITLE
k8s.io libs version are not synchronized

### ISSUE THREAD

**Issue by Ryuko** [eko/monday#197]
This seems to be the issue:
https://github.com/eko/monday/blob/fcd9227ce9d962a7121a34c7cf273e4e66b79d49/go.mod#L14-L16

error assignment is missing here:
https://github.com/eko/monday/blob/8fc717667cfb272932c2025df8c92f7a6b0bb9fd/vendor/k8s.io/client-go/transport/spdy/spdy.go#L46-L50

see:
https://github.com/kubernetes/client-go/blob/fb8b7346aacefea5ee2ab2e234afc4451c90c435/transport/spdy/spdy.go#L46-L51

**Comment by eko** [comment]
Thank you, k8s.io librairies are now aligned:

```
	k8s.io/api v0.30.3
	k8s.io/apimachinery v0.30.3
	k8s.io/client-go v0.30.3
```

Closing this issue for now. Please feel free to reopen if necessary.
