### ISSUE TITLE
Secure one liner script with https

### ISSUE THREAD

**Issue by scottgrover** [eko/monday#2]
Hi there,

I noticed your documentation serves your one liner script over HTTP, instead of HTTPS. This isn't a good practice, as you're recommending the output be piped directly to sh without any validation. If the connection was some how intercepted, a bad actor would be able to run arbitrary code on the developers box without the developer knowing what exactly was ran.

I'd recommend installing SSL and serving your script over HTTPS. If you need help getting SSL set up, I'd be happy to assist. 

Cheers,
Scott

**Comment by eko** [comment]
Hi @scottgrover,

Thank you for your feedback. I am aware that this is not the best security option but this is really nice-to-have option for people that want to start using it quickly.

I just updated the README and now serving the bash script content over HTTPS.

Thank you :)
