### ISSUE TITLE
Linux assumes presence of gedit

### ISSUE THREAD

**Issue by hlascelles** [eko/monday#20]
Simple one: during init on Mint Linux, I see:

```
command not found: gedit
```

This is because [gedit is assumed](https://github.com/eko/monday/blob/7203c942e5c0997a2615c6809bda5a2b6db457c8/cmd/main.go#L86). Mint uses `xed`. Can we make this an ENV, or maybe it could try for both?

**Comment by eko** [comment]
Hi @hlascelles,

Thank you for your feedback and reporting this issue.

I just fixed that: I've added the `xed` editor to an editor list so if you don't have `gedit` installed, it will fallback on `xed`.

Also, I've added an environment variable to force the editor value so you can also use `MONDAY_EDITOR=xed`(or another value) if you want.

I hope it will satisfy your needs. Closing this issue now, feel free to re-open if you have other issues concerning this subject.

This will be shipped into `v1.0.7` version in the coming days.

For more information, see PR https://github.com/eko/monday/pull/22/files

Thank you

**Comment by hlascelles** [comment]
Great, thanks, looks good, I will give the next version a go when it's out. Thank you for jumping on it.

**Comment by hlascelles** [comment]
Works great, thanks!
