### ISSUE TITLE
Install broken (ubuntu 18.04)

### ISSUE THREAD

**Issue by gmistick** [eko/monday#23]
Hi,
First time trying Monday, I worked with the installation guide (curl *.sh | sh ) , but the url that is generated is actually:
https://github.com/eko/monday/releases/download/latest/monday-linux-386
When trying to reach the URL i'm getting to a 404 page.

**Expected behavior**:
Link working :)

**Actual behavior**:
Link is broken

**Platforms**:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by eko** [comment]
Hi @gmistick,

I don't know where you have generated the following URL (which indeed is not correct, `download` and `latest` are inversed):
https://github.com/eko/monday/releases/download/latest/monday-linux-386

Correct is:
https://github.com/eko/monday/releases/latest/download/monday-darwin-386

I can see that:
* https://composieux.fr/getmonday.sh install script already have the correct URL
* https://github.com/eko/monday/blob/master/README.md file also have the correct URL
* upgrade CLI command (https://github.com/eko/monday/blob/master/cmd/upgrade.go#L17) also have the correct URL format

Closing this issue as there is no issue related to the given URL.

Feel free to re-open in case you can give more details about an issue.

Thank you
