### ISSUE TITLE
panic if Dial error in Proxy.handleConnections

### ISSUE THREAD

**Issue by dlecorfec** [eko/monday#27]
﻿pkg/proxy/proxy.go:121: "defer target.Close()" causes a panic if "target, err := net.Dial()" (line 114)  failed. Missing a break/return/continue statement after "p.view.Writef()" line 116? Or juste add a check for nil pointer in the defer statement?

(unable to reproduce the panic, unfortunately)

**Comment by eko** [comment]
Thanks for reporting this David, this is now fixed
