### ISSUE TITLE
Chmod +a not available on Linux

### ISSUE THREAD

**Issue by MelvinLoos** [eko/monday#3]
The +a parameter you use in the README and also in your curl installer script is not available on Linux, this is a Mac only parameter.

I'm running this on ubuntu 18.04 but as far as I know this gives the same error message on other distros:
```bash
chmod: invalid mode: ‘+a’
```

**Comment by eko** [comment]
Hi,

Thank you for your feedback!

I just removed this command from the README file because, indeed, it is not necessary anymore as you run the project using `sudo` so root can edit the `/etc/hosts` file.

**Comment by rmasclef** [comment]
@eko acl chmods are still present in the curl installer script 👍

**Comment by eko** [comment]
@rmasclef @MelvinLoos Thank you, shell script is now up-to-date ;)
