### ISSUE TITLE
Q: how that diagram has been made

### ISSUE THREAD

**Issue by xlab** [eko/monday#39]
Hey! Sorry not a technical issue, I just wondered how this diagram has been created:
![image](https://user-images.githubusercontent.com/477998/72275177-765e8680-363e-11ea-923f-12b7c652c7ad.png)

Are those just stock icons and some simple app or that was some kind of a studio with lots of stock objects? I'm using OmniGraffle and Sketch for all my diagrams, but sometimes I need something more rich that just a colored rectangle :D

That terminal window frame there is dope. Arrows look like it has been declared programmatically i.e. using dot / postscript.

😅

**Comment by eko** [comment]
Hi @xlab,

Thank you for appreciating this diagram,

It has been created using... Google Slides shapes ! Yep... I find it powerful ;)

I close this issue now that you have the answer.
