### ISSUE TITLE
No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by parkee** [eko/monday#5]
Our company uses okta for authentication. When I try to connect do port-forwarding I get the following error:
❌  No Auth Provider found for name "oidc"

Part of our configuration looks like this:
- context:
    cluster: staging.company.com
    user: okta
  name: staging.company.com

- name: okta
  user:
    auth-provider:
      config:
        client-id: clientid
        id-token: token
        idp-issuer-url: https://company.okta.com
      name: oidc

**Comment by eko** [comment]
This issue is not related to Monday: it looks like you have an issue with your Kubernetes configuration.

You should add an authentication provider or maybe you just have an indentation issue in your Kubernetes configuration file?

Thank you

**Comment by parkee** [comment]
@eko 
Do you have any suggestions on how to check it?
All kubectl commands work just fine, I don't have any issues with authentication when calling port-forward directly. So I suppose my configuration should be OK.
I have issues only when trying to use Monday, so my assumption was that Monday doesn't understand external auth providers such as okta.
